language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

install:
  - bash -x devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export PATH=$HOME/miniconda/bin:$PATH

script:
  # Add conda channel
  - conda config --add channels omnia
  - conda config --add channels $ORGNAME
  # Build the recipe
  - conda build devtools/conda-recipe
  # Test the local installation
  - source activate _test
  - conda install --yes --quiet nose nose-timer
  - cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer -a "\!slow" && cd ..

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35

  global:
    - ORGNAME="choderalab" # the name of the organization
    - PACKAGENAME="thermopyl" # the name of your package
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "U7PFV21uR/I1jqxzMFC5I+0e8SNxnE4YbXiIi1ZzWhYBUjIpYvwSDAWgtrYLmVQI+uG8iY0ad3hUWd2RzwB2BWMFe8yhlFqPS5EPJXj+y/YlmeIIcaH8yc+//1fl0S5Fi09cmXWY+Y1+ygmKcXUrSsjqxsNp0G3SoQHhYcWTS64="

after_success:
  - echo "after_success"
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then source devtools/travis-ci/after_success.sh; fi
