package:
  name: thermopyl-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python
    - six
    - pandas
    - pyxb >=1.2.4
    - hdf5

  run:
    - python
    - six
    - pandas
    - pyxb >=1.2.4
    - hdf5

test:
  requires:
    - nose
  imports:
    - thermopyl
  commands:
    - thermoml-archive-update

about:
  home: https://github.com/choderalab/ThermoPyL
  license: GNU Lesser General Public License v2 or later (LGPLv2+)




