package:
  name: thermopyl-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: False  # Not needed for pip/setuptools builds
  number: 0

requirements:
  build:
    - python
    - pip
    - pandas
    - numpy
    - feedparser
    - pytables
  run:
    - python
    - pandas
    - numpy
    - feedparser
    - pytables

test:
  requires:
    - pytest
    - pip
  imports:
    - thermopyl
  commands:
    - pytest thermopyl/tests --maxfail=1 --disable-warnings -v

about:
  home: https://github.com/choderalab/thermopyl
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
