package:
  name: thermopyl-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: False  # Not needed for pip/setuptools builds
  number: 0

requirements:
  build:
    - python
    - pip
    - pandas
    - pyxb ==1.2.6
    - feedparser
    - pytables

  run:
    - python
    - pandas
    - pyxb ==1.2.6
    - feedparser
    - pytables

test:
  requires:
    - nose
    - pip
  imports:
    - thermopyl
  commands:
    - nosetests thermopyl --nocapture --verbosity=2 --with-doctest
    - thermoml-update-mirror
    - thermoml-build-pandas --help
    - thermoml-build-pandas --journalprefix=acs

about:
  home: https://github.com/choderalab/thermopyl
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
